USE [master]
GO

/****** Object:  Database [ContactTrace]    Script Date: 22/05/2021 8:01:30 AM ******/
CREATE DATABASE [ContactTrace]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContactTrace', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ContactTrace.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ContactTrace_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ContactTrace_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContactTrace].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ContactTrace] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ContactTrace] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ContactTrace] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ContactTrace] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ContactTrace] SET ARITHABORT OFF 
GO

ALTER DATABASE [ContactTrace] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ContactTrace] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ContactTrace] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ContactTrace] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ContactTrace] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ContactTrace] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ContactTrace] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ContactTrace] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ContactTrace] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ContactTrace] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ContactTrace] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ContactTrace] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ContactTrace] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ContactTrace] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ContactTrace] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ContactTrace] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ContactTrace] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ContactTrace] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ContactTrace] SET  MULTI_USER 
GO

ALTER DATABASE [ContactTrace] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ContactTrace] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ContactTrace] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ContactTrace] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ContactTrace] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ContactTrace] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ContactTrace] SET  READ_WRITE 
GO

